### ISSUE TITLE
Unity user id not passed through to android properly

### ISSUE THREAD

**Issue by snmaynard** [bugsnag/bugsnag-unity#15] opened 2015-06-18 21:25 UTC
Possibly its being overwritten in the android notifier

**Comment by CodeHex** [comment] 2016-11-14 11:27
I've tried calling `Bugsnag.SetUser` and this seems to be passed on to android reports correctly. The android notifier has been updated multiple times since this issue was raised, so it may have been fixed. Is there any more info about how this occurred @snmaynard?

**Comment by CodeHex** [comment] 2016-11-18 15:22
I'm closing this due to being unable to reproduce it.

**Closed by CodeHex** 2016-11-18 15:22 UTC
Labels: bug
