### ISSUE TITLE
Bugsnag not reporting errors in asynchronous functions on iOS through Xcode

### ISSUE THREAD

**Issue by brendanlet** [bugsnag/bugsnag-unity#154] opened 2019-05-31 18:55 UTC
### Description

I'm working on getting bugsnag properly working in a Unity project I'm working on.

### Issue

Bugsnag does not report errors in asynchronous functions when running the App in Xcode after building to iOS.

### Environment

* bugsnag-unity version: 4.5.1
* Unity version: 2019.1.2f1
* Operating system name and version: Tested on iOS 11.3.1 and 12.3.1
* Target platform names and versions: Testing on iPhone X
* Initialized bugsnag in code

### Example code snippet

```
private async void BreakMe()
    {
        await Task.CompletedTask; //To make function async without warnings

        throw new System.Exception();
    }

```
This method is inside the mainApp game object, and is called in the synchronous awake function.

As a note, bugsnag is working properly when running the project through Unity.

**Comment by kattrali** [comment] 2019-06-03 09:06
Thanks for the report, @brendanlet. I have a few clarification questions:

> As a note, bugsnag is working properly when running the project through Unity.

Do you mean when pressing play in the Unity editor?

Is anything logged in the Xcode console when the error occurs?

> Target platform names and versions: Testing on iPhone X

Actual device or simulator?

**Comment by brendanlet** [comment] 2019-06-03 18:38
> Do you mean when pressing play in the Unity editor?

Yes, I'm not sure of the proper terminology, but that is what I meant.

> Is anything logged in the Xcode console when the error occurs?

```
ARN : BSG_KSCrashSentry.c (109): BSG_KSCrashType bsg_kscrashsentry_installWithContext(BSG_KSCrash_SentryContext *, BSG_KSCrashType, void (*)(char, char *)): KSCrash: App is running in a debugger. Only user reported events will be handled.
Exception: Exception of type 'System.Exception' was thrown.
  at BaseApp..ctor () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Linq.Expressions.StackGuard.RunOnEmptyStack[T1,T2] (System.Action`2[T1,T2] action, T1 arg1, T2 arg2) [0x00000] in <00000000000000000000000000000000>:0 
  at BaseApp.BreakMe () [0x00000] in <00000000000000000000000000000000>:0 
  at BaseApp.Awake () [0x00000] in <00000000000000000000000000000000>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.SendOrPostCallback.Invoke (System.Object state) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.UnitySynchronizationContext.Exec () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.UnitySynchronizationContext.Exec () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.UnitySynchronizationContext:Exec()
UnityEngine.UnitySynchronizationContext:Exec()
 
(Filename: currently not available on il2cpp Line: -1)
```

and then a bit later

```
INFO : BSG_KSCrash.m (325): -[BSG_KSCrash sendAllReportsWithCompletion:]: Sending 0 crash reports
```

This is being run on the actual device. I've run it in both debug and non-debug mode with no success.

**Comment by kattrali** [comment] 2019-06-04 09:15
Ah I see. The first line of the log is the problem:
```
 App is running in a debugger. Only user reported events will be handled.
```

When the debugger is active, crash reporting is disabled by default, as it can interfere with the debugging session. Does crash reporting work if you select Product > Scheme > Edit Scheme in the Xcode menu and uncheck "Debug executable"? (You can also disconnect the device from Xcode and run the app directly from the device)

**Comment by brendanlet** [comment] 2019-06-04 18:30
Unfortunately it still doesn't seem to be working. That message about the debugger doesn't show up anymore, but no crash reports are being sent still.

```
Exception: Broke Correctly
  at BaseApp..ctor () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Linq.Expressions.StackGuard.RunOnEmptyStack[T1,T2] (System.Action`2[T1,T2] action, T1 arg1, T2 arg2) [0x00000] in <00000000000000000000000000000000>:0 
  at BaseApp.BreakMe () [0x00000] in <00000000000000000000000000000000>:0 
  at BaseApp.Awake () [0x00000] in <00000000000000000000000000000000>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.SendOrPostCallback.Invoke (System.Object state) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.UnitySynchronizationContext.Exec () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.UnitySynchronizationContext.Exec () [0x00000] in <00
Exception: Broke Correctly
  at BaseApp..ctor () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Linq.Expressions.StackGuard.RunOnEmptyStack[T1,T2] (System.Action`2[T1,T2] action, T1 arg1, T2 arg2) [0x00000] in <00000000000000000000000000000000>:0 
  at BaseApp.BreakMe () [0x00000] in <00000000000000000000000000000000>:0 
  at BaseApp.Awake () [0x00000] in <00000000000000000000000000000000>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.SendOrPostCallback.Invoke (System.Object state) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.UnitySynchronizationContext.Exec () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.UnitySynchronizationContext.Exec () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.UnitySynchronizationContext:Exec()
UnityEngine.UnitySynchronizationContext:Exec()
 
(Filename: currently not available on il2cpp Line: -1)
```
and later again
```
INFO : BSG_KSCrash.m (325): -[BSG_KSCrash sendAllReportsWithCompletion:]: Sending 0 crash reports
```

The unity project did change somewhat, but nothing that should affect this. The errors are happening but still going unreported.

**Comment by kattrali** [comment] 2019-06-14 15:31
Apologies for the delay. This is what I have so far:

> ```
> INFO : BSG_KSCrash.m (325): -[BSG_KSCrash sendAllReportsWithCompletion:]: Sending 0 crash reports
> ```

This log message can be ignored. It indicates that there were no unsent crash reports from the previous app launch.


Using a similar example, reports seem to be reported normally on 2018.3 but do not appear on 2019.1.

Code:
```c#
using UnityEngine;
using System.Threading;
using System.Threading.Tasks;

public class Runner : MonoBehaviour
{
  void Start() {
    BreakMe();
  }

  private async void BreakMe() {
    await Task.CompletedTask;

    throw new System.Exception("async failure");
  }
}
```

<details>
<summary>Output on 2018.3</summary>
Xcode console:

```
Exception: async failure
  at Runner..ctor () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Linq.Expressions.StackGuard.RunOnEmptyStack[T1,T2] (System.Action`2[T1,T2] action, T1 arg1, T2 arg2) [0x00000] in <00000000000000000000000000000000>:0 
  at Runner.BreakMe () [0x00000] in <00000000000000000000000000000000>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.UnitySynchronizationContext.Exec () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.UnitySynchronizationContext.Exec () [0x00000] in <00000000000000000000000000000000>:0 
```

Bugsnag dashboard:

<img width="987" alt="bugsnag dash" src="https://user-images.githubusercontent.com/333454/59513328-8b114b00-8eb2-11e9-9b07-8ab41347a02d.png">

<img width="986" alt="full trace" src="https://user-images.githubusercontent.com/333454/59513320-85b40080-8eb2-11e9-9093-1ac9c6fed7f6.png">
</details>

I'm looking into what's different about the two Unity versions - I'd expect these to behave the same way.

**Comment by kattrali** [comment] 2019-06-14 16:00
After cleaning my project and caches a few times, it seems to work consistently on 2019.1 as well using the same code as above and bugsnag-unity v4.5.1. I'm not sure what state Unity had gotten into, though the project was upgraded once from a prior version of 2019.1.

Is there any additional information about the project or configuration to help debug what may be causing this?

**Comment by kattrali** [comment] 2019-06-26 08:45
Hey @brendanlet, are you still seeing this? If so, please drop in a comment or reach out at support@bugsnag.com. I'm closing this issue, though only because I haven't managed to consistently reproduce this and its been a while since the last time we had an update. I'll reopen if anything new arises. Thanks!

**Closed by kattrali** 2019-06-26 08:45 UTC
Labels: awaiting user feedback
