### ISSUE TITLE
[Android] java.lang.Error causing tgkill after upgrading unity

### ISSUE THREAD

**Issue by Sh3rawi** [bugsnag/bugsnag-unity#206] opened 2020-10-08 09:56 UTC
### Describe the bug
We have a unity project that was on the 2018.4 LTS, and after upgrading to 2019.4 LTS we started seeing a couple of crashes on specific devices/os versions, that were consistent always and ended up with a java.lang.Error signal 6 crash. Commenting out the initialization and usage of bugsnag in our c# code was enough to stop all these weird crashes from hapenning.
While debugging, we noticed that these crashes started happening on 2019.2 and after, while testing on an upgrade to 2019.1 the problem never appeared. Unity changed the way they import/use the androidjni module on 2019.2, which might be a reason for this weird behaviour.

### Steps to reproduce
We couldn't reproduce it but on our actual production use-case.

### Environment
* Bugsnag version: 4.8.2
* Unity version: 2019.4.9f1
* iOS/Android/macOS/Windows/browser version: Android 8
* simulator/emulator or physical device: Physical Device - Huawei Mate 10 Lite
* Initializing bugsnag via a Unity GameObject or in code?: Code
* Player Settings:
    * Scripting backend (Mono or IL2CPP): Both
    * API compatibility level for .NET: 4.x
    * Stack Trace level for all error types (None/ScriptOnly/Full): Script Only

```
Caused by java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Version '2019.4.9f1 (50fe8a171dd9)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
Build fingerprint: 'HUAWEI/LDN-L21B/HWLDN-Q:8.0.0/HUAWEILDN-L21/166(C185):user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2020-10-08 09:37:17+0300
pid: 15806, tid: 17100, name: UnityMain  >>> com.boundless.jawaker <<<
uid: 10249
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
    x0  0000000000000000  x1  00000000000042cc  x2  0000000000000006  x3  0000000000000008
    x4  000000007645b0c0  x5  000000007645b0c0  x6  000000007645b0c0  x7  000000007645b200
    x8  0000000000000083  x9  111f4897e6198655  x10 00000075652d3588  x11 111f4897e6198655
    x12 111f4897e6198655  x13 0000000000000020  x14 000000758773090c  x15 111f4897e6198655
    x16 00000075877eb2d8  x17 000000758777ea38  x18 0000000000000010  x19 0000000000003dbe
    x20 00000000000042cc  x21 000000757233f4c0  x22 000000000000000b  x23 00000075652d2689
    x24 0000000000000051  x25 00000075830623b0  x26 0000000000000244  x27 00000075834f947b
    x28 0000000000000043  x29 00000075652d25f0
    sp  00000075652d25b0  lr  0000007587724394  pc  000000758777ea40

backtrace:
      #00 pc 0000000000078a40  /system/lib64/libc.so (tgkill+8) (BuildId: b5934c95dd5853f7ffd9b057a52ab13e)
      #01 pc 000000000001e390  /system/lib64/libc.so (abort+88) (BuildId: b5934c95dd5853f7ffd9b057a52ab13e)
      #02 pc 000000000047b418  /system/lib64/libart.so (art::Runtime::PreZygoteFork()) (BuildId: d5abbb207b704ae580a598ed2f6f9d4f)
      #03 pc 000000000047bb64  /system/lib64/libart.so (art::Runtime::Create(art::RuntimeArgumentMap&&)) (BuildId: d5abbb207b704ae580a598ed2f6f9d4f)
      #04 pc 00000000005744c4  /system/lib64/libart.so (android::base::LogMessage::~LogMessage()+852) (BuildId: d5abbb207b704ae580a598ed2f6f9d4f)
      #05 pc 00000000004a96ac  /system/lib64/libart.so (art::Thread::AssertNoPendingExceptionForNewException(char const*) const+1184) (BuildId: d5abbb207b704ae580a598ed2f6f9d4f)
      #06 pc 000000000049fc0c  /system/lib64/libart.so (art::Thread::ThrowOutOfMemoryError(char const*)+200) (BuildId: d5abbb207b704ae580a598ed2f6f9d4f)
      #07 pc 000000000037eff4  /system/lib64/libart.so (art::JNI::EnsureLocalCapacityInternal(art::ScopedObjectAccess&, int, char const*)+104) (BuildId: d5abbb207b704ae580a598ed2f6f9d4f)
      #08 pc 000000000033c7a4  /system/lib64/libart.so (art::JNI::PushLocalFrame(_JNIEnv*, int)+616) (BuildId: d5abbb207b704ae580a598ed2f6f9d4f)
      #09 pc 00000000008e8988  /data/app/com.boundless.jawaker-Ka8k_E79giJZ6UFIIP7Hng==/lib/arm64/libunity.so (BuildId: da6ca9ca9f1345ae56e4125c2cd427e2ed5f6bd6)

       at libc.tgkill(tgkill:8)
       at libc.abort(abort:88)
       at libart.art::Runtime::PreZygoteFork()(PreZygoteFork)
       at libart.art::Runtime::Create(art::RuntimeArgumentMap&&)(Create)
       at libart.android::base::LogMessage::~LogMessage()(~LogMessage:852)
       at libart.art::Thread::AssertNoPendingExceptionForNewException(char const*) const(AssertNoPendingExceptionForNewException:1184)
       at libart.art::Thread::ThrowOutOfMemoryError(char const*)(ThrowOutOfMemoryError:200)
       at libart.art::JNI::EnsureLocalCapacityInternal(art::ScopedObjectAccess&, int, char const*)(EnsureLocalCapacityInternal:104)
       at libart.art::JNI::PushLocalFrame(_JNIEnv*, int)(PushLocalFrame:616)
       at libunity.0x8e8988()
```

**Comment by mattdyoung** [comment] 2020-10-08 12:59
Hi @Sh3rawi

It would be useful if you could share the configuration options you're using for the Bugsnag SDK and whether you're configuring this in a Bugsnag game object or in code.
 
Do you still see the issue if you upgrade the Bugsnag dependency to the latest version?

This looks like an out of memory issue. Do you have any more info on the state of the device / app at the time of the crash?

**Comment by Sh3rawi** [comment] 2020-10-13 12:02
Hi @mattdyoung,
Here is the configuration we use:
```        
Bugsnag.Init(key);
Bugsnag.Configuration.AutoDetectAnrs = true;
Bugsnag.Configuration.ReleaseStage = DeviceHelper.IsTestBuild() ? "development" : "production";
Bugsnag.BeforeNotify(report => {
  report.Metadata.Add("app_env", new Dictionary<string, string>() {
    { "screen", OurSceneManager.GetActiveScene() },
    { "game_id", GameStore.Read("id", 0).ToString() },
    { "game_module", GameStore.gameModuleName },
    { "social_view_open", SocialViewManager.socialViewActive.ToString() }
  });
});
```
I've verified that all 4.8.x version have the same crash:
```
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495] Runtime aborting...
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495] Aborting thread:
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495] "UnityMain" prio=5 tid=32 Runnable
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   | group="" sCount=0 dsCount=0 flags=0 obj=0x135465b0 self=0xea466c00
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   | sysTid=7355 nice=0 cgrp=default sched=0/0 handle=0xc4a4f970
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   | state=R schedstat=( 19526205162 208455215 4178 ) utm=1865 stm=87 core=5 HZ=100
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   | stack=0xc494d000-0xc494f000 stackSize=1038KB
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   | held mutexes= "abort lock" "mutator lock"(shared held)
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   native: #00 pc 002c6aa3  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+130)
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   native: #01 pc 00359273  /system/lib/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMapb+202)
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   native: #02 pc 00355757  /system/lib/libart.so (_ZNK3art6Thread4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMapb+34)
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   native: #03 pc 00346015  /system/lib/libart.so (_ZNK3art10AbortState10DumpThreadERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEPNS_6ThreadE+28)
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   native: #04 pc 00345df7  /system/lib/libart.so (_ZNK3art10AbortState4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+346)
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   native: #05 pc 0033a7b7  /system/lib/libart.so (_ZN3art7Runtime5AbortEPKc+110)
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   native: #06 pc 0033aeb3  /system/lib/libart.so (_ZN3art7Runtime7AborterEPKc+10)
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   native: #07 pc 003f3419  /system/lib/libart.so (_ZN7android4base10LogMessageD1Ev+456)
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   native: #08 pc 0035db85  /system/lib/libart.so (_ZNK3art6Thread39AssertNoPendingExceptionForNewExceptionEPKc+872)
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   native: #09 pc 003557e5  /system/lib/libart.so (_ZN3art6Thread21ThrowOutOfMemoryErrorEPKc+132)
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   native: #10 pc 002921bb  /system/lib/libart.so (_ZN3art3JNI27EnsureLocalCapacityInternalERNS_18ScopedObjectAccessEiPKc+146)
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   native: #11 pc 0025fc37  /system/lib/libart.so (_ZN3art3JNI14PushLocalFrameEP7_JNIEnvi+418)
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   native: #12 pc 00cbe6ff  /data/app/com.boundless.jawaker-pFuEZLECZF28nOIMmTigxA==/lib/arm/libunity.so (???)
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   at com.unity3d.player.UnityPlayer.nativeRender(Native method)
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   at com.unity3d.player.UnityPlayer.access$300(unavailable:-1)
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   at com.unity3d.player.UnityPlayer$e$1.handleMessage(unavailable:-1)
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   at android.os.Handler.dispatchMessage(Handler.java:104)
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   at android.os.Looper.loop(Looper.java:166)
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   at com.unity3d.player.UnityPlayer$e.run(unavailable:-1)
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495] Pending exception java.lang.OutOfMemoryError: PushLocalFrame
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   at boolean com.unity3d.player.UnityPlayer.nativeRender() ((null):-2)
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   at boolean com.unity3d.player.UnityPlayer.access$300(com.unity3d.player.UnityPlayer) ((null):-1)
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   at boolean com.unity3d.player.UnityPlayer$e$1.handleMessage(android.os.Message) ((null):-1)
10-13 15:00:35.201  7293  7355 F zygote  : runtime.cc:495]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:104)
```

We've also verified that the app before and after our Unity version upgrade uses the same amount of memory and its way below what the device can offer us.

**Comment by Sh3rawi** [comment] 2020-11-12 16:24
@mattdyoung @phillipsam any updates on this?

**Comment by mattdyoung** [comment] 2020-11-16 10:51
@Sh3rawi 
We haven't yet been able to reproduce the behavior. I know initially you said you couldn't reproduce this outside of production. Is that still the case or have you been able to trigger the issue when testing?

**Comment by phillipsam** [comment] 2021-02-04 15:05
Hi @Sh3rawi we believe that we have now been able to reproduce what you are seeing. We are working on a fix for this and will post back here with any updates.

**Comment by phillipsam** [comment] 2021-03-05 18:20
Hi @Sh3rawi can you please try upgrading to [v4.8.5](https://github.com/bugsnag/bugsnag-unity/releases/tag/v4.8.5) and verify that this fixes the issue you are seeing?

**Comment by phillipsam** [comment] 2021-03-18 20:38
Closing this off as a fix has been released for this. Do comment below if you have any further questions.

**Closed by phillipsam** 2021-03-18 20:38 UTC
Labels: awaiting feedback, bug, released
