### ISSUE TITLE
Android Crash on start 

### ISSUE THREAD

**Issue by willispinaud** [bugsnag/bugsnag-unity#88] opened 2018-08-21 22:34 UTC
### Description
Trying to install the alpha version on Bugsnag on our Unity project

### Issue
When starting the application it crashes

### Environment

* bugsnag-unity version: 4.0.0 alpha 1
* Unity version: 2017.4.9f1
* Operating system name and version: MacOs 10.13.5
* Target platform names and versions: Android 6.0.1
* Initializing bugsnag via the Unity UI or in code? Code

### Bug report

```cs
                   art  E  JNI ERROR (app bug): accessed stale local reference 0x200001 (index 0 in a table of size 0)
                         F  art/runtime/indirect_reference_table.cc:67] JNI ERROR (app bug): see above.
        google-breakpad  W  ### ### ### ### ### ### ### ### ### ### ### ### ###
                         W  Chrome build fingerprint:
                         W  68.0.3440.91
                         W  344009150
                         W  ### ### ### ### ### ### ### ### ### ### ### ### ###
                  CRASH  E  signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr da8d0000
                         E  *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
                         E  Build fingerprint: 'Verizon/nobleltevzw/nobleltevzw:6.0.1/MMB29K/N920VVRS2BPF2:user/release-keys'
                         E  Revision: '9'
                         E  pid: 32461, tid: 306, name: Thread-2392  >>> com.************.********** <<<
                         E      r0 00000000  r1 00000000  r2 0001f3c4  r3 da8d0000
                         E      r4 da8cdfbc  r5 da8cdf40  r6 e9b443b9  r7 da8ce020
                         E      r8 00000000  r9 da8cdf50  sl c69c9a80  fp da8cdfbc
                         E      ip 00000004  sp da8cded4  lr f612cd61  pc f74b0a98  cpsr eeb61c4c
                         E  backtrace:
                         E      #00  pc 00017a98  /system/lib/libc.so (memset+48)
                         E      #01  pc 00009d5d  /system/lib/libunwind.so (_Uarm_local_access_addr_space_init+8)
                         E      #02  pc e9b4608c  <unknown/absolute>
                         E  stack:
                         E           da8cde94  ffffffff
                         E           da8cde98  ffffffff
                         E           da8cde9c  00000000
                         E           da8cdea0  00000000
                         E           da8cdea4  00000000
                         E           da8cdea8  00000032
                         E           da8cdeac  0000001f
                         E           da8cdeb0  da8cdf40
                         E           da8cdeb4  e9b4439a
                         E           da8cdeb8  da8ce020
                         E           da8cdebc  00000005
                         E           da8cdec0  da8cdf50
                         E           da8cdec4  00000000
                         E           da8cdec8  c69c9a80  [anon:libc_malloc]
                         E           da8cdecc  e9b460a8
                         E           da8cded0  00000000
                         E      #00  da8cded4  da8cdfbc
                         E           ........  ........
                         E      #01  da8cded4  da8cdfbc
                         E           da8cded8  e9b46090
                         E      #02  da8cdedc  f612c247  /system/lib/libunwind.so
                         E           da8cdee0  ffffffff
                         E           da8cdee4  00000000
                         E           da8cdee8  00001000
                         E           da8cdeec  00000001
                         E           da8cdef0  00000000
                         E           da8cdef4  00000037
                         E           da8cdef8  e9b45000
                         E           da8cdefc  e9b460c0
                         E           da8cdf00  0000002d
                         E           da8cdf04  da8cdf3c
                         E           da8cdf08  e9b443b9
                         E           da8cdf0c  00007ecd
                         E           da8cdf10  e9b4439a
                         E           da8cdf14  f7513ec0
                         E           da8cdf18  da8cdf34
                         E  memory near r2:
                         E      0001f3a4 ffffffff ffffffff ffffffff ffffffff  ................
                         E      0001f3b4 ffffffff ffffffff ffffffff ffffffff  ................
                         E      0001f3c4 ffffffff ffffffff ffffffff ffffffff  ................
                         E      0001f3d4 ffffffff ffffffff ffffffff ffffffff  ................
                         E      0001f3e4 ffffffff ffffffff ffffffff ffffffff  ................
                         E      0001f3f4 ffffffff ffffffff ffffffff ffffffff  ................
                         E      0001f404 ffffffff ffffffff ffffffff ffffffff  ................
                         E      0001f414 ffffffff ffffffff ffffffff ffffffff  ................
                         E      0001f424 ffffffff ffffffff ffffffff ffffffff  ................
                         E      0001f434 ffffffff ffffffff ffffffff ffffffff  ................
                         E      0001f444 ffffffff ffffffff ffffffff ffffffff  ................
                         E      0001f454 ffffffff ffffffff ffffffff ffffffff  ................
                         E      0001f464 ffffffff ffffffff ffffffff ffffffff  ................
                         E      0001f474 ffffffff ffffffff ffffffff ffffffff  ................
                         E      0001f484 ffffffff ffffffff ffffffff ffffffff  ................
                         E      0001f494 ffffffff ffffffff ffffffff ffffffff  ................
                         E  code around pc:
                         E      f74b0a78 e1a01c01 e1811421 e1811821 e213c007  ....!...!.......
                         E      f74b0a88 1a000024 e1a00001 e2522040 3a00000a  $.......@ R....:
                         E      f74b0a98 e1c300f0 e1c300f8 e1c301f0 e1c301f8  ................
                         E      f74b0aa8 e1c302f0 e1c302f8 e1c303f0 e1c303f8  ................
                         E      f74b0ab8 e2833040 e2522040 aafffff4 e2822040  @0..@ R.....@ ..
                         E      f74b0ac8 e1b0cd82 3a000004 e1c300f0 e1c300f8  .......:........
                         E      f74b0ad8 e1c301f0 e1c301f8 e2833020 5a000002  ........ 0.....Z
                         E      f74b0ae8 e1c300f0 e1c300f8 e2833010 e1b0ce82  .........0......
                         E      f74b0af8 3a000000 e0c300f8 5a000000 e4831004  ...:.......Z....
                         E      f74b0b08 e1b0cf82 14c31001 24c31001 25c31000  ...........$...%
                         E      f74b0b18 e8bd0001 e12fff1e e26cc008 e042200c  ....../...l.. B.
                         E      f74b0b28 e1b00f8c 44c31001 24c31001 24c31001  .......D...$...$
                         E      f74b0b38 e35c0004 3affffd2 e4831004 eaffffd0  ..\....:........
                         E      f74b0b48 eec01b10 e1b0ce82 3a000000 f400070d  ...........:....
                         E      f74b0b58 aa000000 f480080d e1b0cf82 44c01001  ...............D
                         E      f74b0b68 24c01001 24c01001 e8bd0001 e12fff1e  ...$...$....../.
                         E  code around lr:
                         E      f612cd40 2024f845 f855bdf8 60311024 f06fbdf8  E.$ ..U.$.1`..o.
                         E      f612cd50 bdf80002 2100b510 46044a03 ea58f7f8  .......!.J.F..X.
                         E      f612cd60 447b4b02 bd1060e3 00021448 ffffff47  .K{D.`..H...G...
                         E      f612cd70 2100b510 4a154c16 4620447c ea48f7f8  ...!.L.J|D F..H.
                         E      f612cd80 49142301 4a154814 4b156263 68094479  .#.I.H.Jcb.KyD.h
                         E      f612cd90 68004478 6061447a 447b4912 48126020  xD.hzDa`.I{D `.H
                         E      f612cda0 4a1260a2 4b1260e3 44784479 6812447a  .`.J.`.KyDxDzD.h
                         E      f612cdb0 21006161 6120447b 61a24620 61e3460a  aa.!{D a F.a.F.a
                         E      f612cdc0 fc1df7f8 4010e8bd bb94f7ff 00021448  .......@....H...
                         E      f612cdd0 0000b2e0 00007128 00007128 fffffef5  ....(q..(q......
                         E      f612cde0 fffffeff ffffff3b ffffff73 00007110  ....;...s....q..
                         E      f612cdf0 ffffff05 b085b530 a8044605 0006e900  ....0....F......
                         E      f612ce00 461a9902 b9199c03 f06fb914 e00d0002  ...F......o.....
                         E      f612ce10 0c02f014 682b6868 9300d004 69042300  ....hh+h.....#.i
                         E      f612ce20 e00347a0 46639300 47a868c5 bd30b005  .G....cF.h.G..0.
                         E      f612ce30 b5734b62 460d4604 681b447b b9086818  bKs..F.F{D.h.h..
             System.err  W  remove failed: ENOENT (No such file or directory) : /data/user/0/com.************.**********/files/AppEventsLogger.persistedevents
om.facebook.FacebookSdk  D  getGraphApiVersion: v3.0
           ViewRootImpl  D  ViewPostImeInputStage processPointer 0
                  CRASH  E  other thread is trapped; signum = 11
     InputEventReceiver  E  Exception dispatching input event.
       MessageQueue-JNI  E  Exception in MessageQueue callback: handleReceiveCallback
                         E  java.lang.Error: signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr da8d0000
                         E  Build fingerprint: 'Verizon/nobleltevzw/nobleltevzw:6.0.1/MMB29K/N920VVRS2BPF2:user/release-keys'
                         E  Revision: '9'
                         E  pid: 32461, tid: 306, name: Thread-2392  >>> com.************.********** <<<
                         E      r0 00000000  r1 00000000  r2 0001f3c4  r3 da8d0000
                         E      r4 da8cdfbc  r5 da8cdf40  r6 e9b443b9  r7 da8ce020
                         E      r8 00000000  r9 da8cdf50  sl c69c9a80  fp da8cdfbc
                         E      ip 00000004  sp da8cded4  lr f612cd61  pc f74b0a98  cpsr eeb61c4c
                         E      at libc.memset(memset:48)
                         E      at libunwind._Uarm_local_access_addr_space_init(_Uarm_local_access_addr_space_init:8)
                         E      at Unknown.0000208c(Unknown Source)
```

**Comment by willispinaud** [comment] 2018-08-21 22:54
Tested with v3.6.6 (2018-05-24).
Crash is not happening with this version.

**Comment by martin308** [comment] 2018-08-21 23:45
@willispinaud thanks for trying out the alpha!

Is there anymore of the log that you can share?

Are you upgrading your application from an old version of Bugsnag or are you installing the Bugsnag package into an application that hasn't had Bugsnag installed before?

Which methods are you calling in the Bugsnag codebase?

I will assemble your collection of versions you mentioned to see if I can reproduce this.

**Comment by martin308** [comment] 2018-08-22 18:12
I've managed to reproduce this with android 6, investigating the cause and a fix now

**Comment by snmaynard** [comment] 2018-09-15 00:44
This has been fixed in the latest alpha's so I'm closing. Thanks for the report @willispinaud and @martin308 for the fix!

**Closed by snmaynard** 2018-09-15 00:44 UTC
