### ISSUE TITLE
3.0.0 bugsnag-unity plugin iOS compile error when using C++98

### ISSUE THREAD

**Issue by Salada** [bugsnag/bugsnag-unity#23] opened 2016-06-14 03:22 UTC
I got this message during xcode compile.

```
CompileC build/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/armv7/NSString+Demangle.o /Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/Assets/Plugins/iOS/NSString+Demangle.mm normal armv7 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/build/il2cpp/XxxxClient.ipa
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/xxxx/work/android-sdk/platform-tools:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c++ -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -stdlib=libc++ -fobjc-arc -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wdeprecated-implementations -Wno-c++11-extensions -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Winvalid-offsetof -miphoneos-version-min=6.0 -g -fvisibility=hidden -fvisibility-inlines-hidden -Wno-sign-conversion -iquote /Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/build/il2cpp/XxxxClient.ipa/build/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/inhouse-generated-files.hmap -I/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/build/il2cpp/XxxxClient.ipa/build/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/inhouse-own-target-headers.hmap -I/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/build/il2cpp/XxxxClient.ipa/build/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/inhouse-all-target-headers.hmap -iquote /Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/build/il2cpp/XxxxClient.ipa/build/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/inhouse-project-headers.hmap -I/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/build/ios/build/Unity-iPhone.build/include -I/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/build/il2cpp/XxxxClient.ipa/Classes -I/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/build/il2cpp/XxxxClient.ipa -I/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/build/il2cpp/XxxxClient.ipa/Classes/Native -I/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/build/il2cpp/XxxxClient.ipa/Libraries/bdwgc/include -I/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/build/il2cpp/XxxxClient.ipa/Libraries/libil2cpp/include -I/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/build/il2cpp/XxxxClient.ipa/../../../../Libs/ScaleForm/Src -I/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/build/il2cpp/XxxxClient.ipa/../../../../Libs/ScaleForm/Integrations/Unity/Src -I/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/build/il2cpp/XxxxClient.ipa/../../../../Libs/ScaleForm/Include -I/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/build/il2cpp/XxxxClient.ipa/../../../../Libs/ProudNet/include -I/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/build/il2cpp/XxxxClient.ipa/build/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/DerivedSources/armv7 -I/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/build/il2cpp/XxxxClient.ipa/build/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/DerivedSources -F/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/build/ios/build/Unity-iPhone.build -F/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/Assets/Plugins/iOS -F/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/Assets/Plugins/iOS/FacebookSDKStrings.bundle -F/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/Assets/Plugins/iOS/Resources -F/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/Assets/Plugins/iOS/Toy -F/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/Assets/Plugins/iOS/FacebookSDKStrings.bundle/Resources -F/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/Assets/Plugins/iOS/Resources/TapjoyResources.bundle -F/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/build/il2cpp/XxxxClient.ipa/Frameworks/Plugins/iOS -mno-thumb -DINIT_SCRIPTING_BACKEND=1 -include /var/folders/rf/c5c8pbbx1572rxyy_f99mrg40000gn/C/com.apple.DeveloperTools/7.3.1-7D1014/Xcode/SharedPrecompiledHeaders/Prefix-agwqmmdhjojnoccuuhsuvhmgsxiw/Prefix.pch -MMD -MT dependencies -MF /Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/build/il2cpp/XxxxClient.ipa/build/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/armv7/NSString+Demangle.d --serialize-diagnostics /Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/build/il2cpp/XxxxClient.ipa/build/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/armv7/NSString+Demangle.dia -c /Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/Assets/Plugins/iOS/NSString+Demangle.mm -o /Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/build/il2cpp/XxxxClient.ipa/build/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/armv7/NSString+Demangle.o
In file included from /Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/Assets/Plugins/iOS/NSString+Demangle.mm:29:
/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/Assets/Plugins/iOS/Demangle.h:154:17: error: union member 'TextPayload' has a non-trivial copy constructor
    std::string TextPayload;
                ^
In file included from /Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/Assets/Plugins/iOS/NSString+Demangle.mm:29:
In file included from /Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/Assets/Plugins/iOS/Demangle.h:17:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:1333:5: note: because type 'std::__1::basic_string<char>' has a user-provided copy constructor
    basic_string(const basic_string& __str);
    ^
In file included from /Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/Assets/Plugins/iOS/NSString+Demangle.mm:29:
/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/Assets/Plugins/iOS/Demangle.h:167:11: error: use of undeclared identifier 'TextPayload'
    new (&TextPayload) std::string(std::move(t));
          ^
/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/Assets/Plugins/iOS/Demangle.h:171:5: error: use of undeclared identifier 'IndexPayload'
    IndexPayload = index;
    ^
/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/Assets/Plugins/iOS/Demangle.h:186:12: error: use of undeclared identifier 'TextPayload'
    return TextPayload;
           ^
/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/Assets/Plugins/iOS/Demangle.h:192:12: error: use of undeclared identifier 'IndexPayload'
    return IndexPayload;
           ^
/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/Assets/Plugins/iOS/Demangle.h:362:28: error: no matching constructor for initialization of 'swift::Demangle::Node'
    return NodePointer(new Node(K, std::move(Text)));
                           ^    ~~~~~~~~~~~~~~~~~~
/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/Assets/Plugins/iOS/Demangle.h:165:3: note: candidate constructor not viable: no known conversion from 'std::__1::basic_string<char>' to 'std::string &&' (aka 'basic_string<char, char_traits<char>, allocator<char> > &&') for 2nd argument
  Node(Kind k, std::string &&t)
  ^
/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/Assets/Plugins/iOS/Demangle.h:169:3: note: candidate constructor not viable: no known conversion from 'std::__1::basic_string<char>' to 'IndexType' (aka 'unsigned long long') for 2nd argument
  Node(Kind k, IndexType index)
  ^
/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/Assets/Plugins/iOS/Demangle.h:162:3: note: candidate constructor not viable: requires single argument 'k', but 2 arguments were provided
  Node(Kind k)
  ^
/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/Assets/Plugins/iOS/Demangle.h:173:3: note: candidate constructor not viable: requires 1 argument, but 2 were provided
  Node(const Node &) = delete;
  ^
/Users/Xxxx/UnityJenkinsNode/workspace/Xxxx/alpha/IOS/XxxxGITDev/NClient/Assets/Plugins/iOS/Demangle.h:405:35: error: rvalue reference to type 'basic_string<[3 * ...]>' cannot bind to lvalue of type 'basic_string<[3 * ...]>'
  std::string &&str() && { return std::move(Stream); }
                                  ^~~~~~~~~~~~~~~~~
7 errors generated.

** BUILD FAILED **
```

i share my xcode compile setting

```
DEBUG_INFORMATION_FORMAT = dwarf-with-dsym
GCC_ENABLE_CPP_EXCEPTIONS = YES
GCC_ENABLE_CPP_RTTI = YES
GCC_ENABLE_OBJC_EXCEPTIONS = YES
CLANG_CXX_LANGUAGE_STANDARD = compiler-default
CLANG_CXX_LIBRARY = libc++
CLANG_ENABLE_OBJC_ARC = YES
```

if problem casued by standard library or compiler setting, I cannot change my build setting. 
this setting is forced by another 3rd-party library.

thanks.

**Comment by kattrali** [comment] 2016-06-14 16:17
Thank you for the report, @Salada, we are taking a look.

**Comment by kattrali** [comment] 2016-06-17 00:00
After a bit of investigating, this is indeed caused by the C++ Language Dialect setting (`CLANG_CXX_LANGUAGE_STANDARD = compiler-default`), as Bugsnag requires at least C++11 to run. Would it be possible to update to at least that setting? I could also try testing with the third-party framework, if you don't mind sharing which one you are using so I can test with an example project.

**Comment by Salada** [comment] 2016-06-20 01:31
Thank you for the reply.

Unfortunately it is to hard to change c++ language dialect setting in our project.

and sorry, ask for understanding i don't share the above mentioned third-part framework.

we use commercial product as server framework [ProudNet](https://ndn.nettention.com/general/download/). and this product force its setting on our project. then i do not provide this framework directly.

if possible, i want to receive bugsnag-unity as static library (.a extensions / fat binary form) not raw code. probably it would be considered any conflicts will not occur.

**Comment by kattrali** [comment] 2016-06-20 09:13
> we use commercial product as server framework ProudNet. and this product force its setting on our project. then i do not provide this framework directly.

Gotcha. Thanks for the link. I'm taking a look at the framework to see if its something we can work around at a later date. 

> if possible, i want to receive bugsnag-unity as static library (.a extensions / fat binary form) not raw code. probably it would be considered any conflicts will not occur.

It may be possible, though it would need a fair amount of testing to ensure there are no conflicts at runtime resulting in unexpected behavior. You could potentially try by compiling the [unity variant of bugsnag-cocoa](https://github.com/bugsnag/bugsnag-cocoa/tree/unity-latest) directly.

I'm closing this out for now as I don't have an immediate change to make in the library, though it is something to revisit for a major revision, if this is a prevalent problem.

**Closed by kattrali** 2016-06-20 09:13 UTC
Labels: bug
