### ISSUE TITLE
v4.6.7 iOS PostProcessBuild fails

### ISSUE THREAD

**Issue by dchau28** [bugsnag/bugsnag-unity#181] opened 2019-11-28 18:31 UTC
We're getting this error building iOS after integrating Bugsnag v4.6.7.  We have other 3rd party libraries already integrated that also make modifications to the XCode project.

```ArgumentNullException: Value cannot be null.
Parameter name: node
System.Collections.Generic.LinkedList`1[T].ValidateNode (System.Collections.Generic.LinkedListNode`1[T] node) (at <d2957de1c3fd4781a43d89572183136c>:0)
System.Collections.Generic.LinkedList`1[T].AddBefore (System.Collections.Generic.LinkedListNode`1[T] node, T value) (at <d2957de1c3fd4781a43d89572183136c>:0)
BugsnagUnity.PostProcessBuild.Apply (System.Collections.Generic.LinkedList`1[T] lines, System.String symbolScriptUploadUuid) (at <fcf4c46fc47147ee98aa67bb67d63f8c>:0)
BugsnagUnity.PostProcessBuild.Apply (System.Collections.Generic.LinkedList`1[T] lines) (at <fcf4c46fc47147ee98aa67bb67d63f8c>:0)
BugsnagUnity.BugsnagBehaviourEditor.OnPostProcessBuild (UnityEditor.BuildTarget target, System.String path) (at Assets/_hothead/thirdparty/code/Bugsnag/BugsnagBehaviour.cs:156)
```

**Comment by mattdyoung** [comment] 2019-11-29 09:28
Hi @dchau28 

Without knowing what other modifications are being made to the XCode project and exactly what the error is that's being reported we won't be able to pinpoint the cause.

Can you share a cut down project as a reproduction case that we can run to investigate this?

**Comment by dchau28** [comment] 2019-11-29 17:35
Hi @mattdyoung 

I could send you a copy of our XCode project from right before BugsnagUnity.PostProcessBuild.Apply is called?

**Comment by mattdyoung** [comment] 2019-12-02 12:28
Hi @dchau28 

Yes, that may be enough for us to reproduce. If you'd rather not share the project code publicly here then you can email it to support@bugsnag.com mentioning this issue.

**Comment by dchau28** [comment] 2019-12-03 17:34
Hi @mattdyoung 

I emailed a link to the XCode project to support@bugsnag.com

**Comment by mattdyoung** [comment] 2020-02-28 13:29
We weren't able to reproduce this so closing.

**Closed by mattdyoung** 2020-02-28 13:29 UTC
